spring:
  datasource:
    url: ${SPRING_DATABASE_URL}
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jwt:
    tokenExpirationTime: ${JWT_TOKEN_EXPIRATION_TIME}
    refreshTokenExpTime: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
    secret: ${JWT_SECRET_KEY}
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client-id: ${GOOGLE_CLIENT_ID}
    callback: ${GOOGLE_REDIRECT_URL}
    secret: ${GOOGLE_CLIENT_SECRET}
    token: https://oauth2.googleapis.com/token

gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}
server:
  ssl:
    key-store: /etc/letsencrypt/live/hearo-server.shop/keystore.p12
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}
